version: '3.7'  

services:
  loadbalancer:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
    networks:
      funjo-net:
        ipv4_address: 172.28.0.6

  app1:
    build: ./app
    environment:
      - DATABASE_URL=postgresql://user:url1234@db-master:5432/url_db
      - CACHE_URL=redis://cache:6379
    depends_on:
      - db-master
      - cache
    networks:
      funjo-net:
        ipv4_address: 172.28.0.4

  app2:
    build: ./app
    environment:
      - DATABASE_URL=postgresql://user:url1234@db-master:5432/url_db
      - CACHE_URL=redis://cache:6379
    depends_on:
      - db-master
      - cache
    networks:
      funjo-net:
        ipv4_address: 172.28.0.5

  db-master:
    image: postgres:latest
    environment:
      POSTGRES_DB: url_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: url1234
      # 복제 설정 추가
      PGMASTER: "true"  # 마스터 설정
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/master/init.sql:/docker-entrypoint-initdb.d/init.sql  
    networks:
      funjo-net:
        ipv4_address: 172.28.0.2

  db-slave:
    image: postgres:latest
    environment:
      POSTGRES_DB: url_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: url1234
      # 마스터 DB에 대한 연결 정보 추가
      REPLICATION_MODE: "slave"  # 슬레이브 설정
      MASTER_HOST: db-master  # 마스터의 서비스 이름
      MASTER_PORT: 5432
      MASTER_USER: user
      MASTER_PASSWORD: url1234
    volumes:
      - db-data-slave:/var/lib/postgresql/data
      - ./db/slave/init_replication.sh:/docker-entrypoint-initdb.d/init_replication.sh
    networks:
      funjo-net:
        ipv4_address: 172.28.0.3

  cache:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      funjo-net:
        ipv4_address: 172.28.0.7

networks:
  funjo-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16  

volumes:
  db-data:
  db-data-slave:
