version: '3.8'

networks:
  url-service-network:
    external: true

services:
  load_balancer:
    image: nginx:1.27.2-bookworm
    ports:
      - "8080:8080"
    volumes:
      - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - url_service1
      - url_service2
    networks:
      url-service-network:
        ipv4_address: 172.18.0.6

  url_service1:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5051:5959"
    networks:
      url-service-network:
        ipv4_address: 172.18.0.7

  url_service2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5052:5959"
    networks:
      url-service-network:
        ipv4_address: 172.18.0.8
