version: '3.8'

networks:
  url-service-network:
    external: true

services:
  master-pg-0:
    image: bitnami/postgresql-repmgr:14-debian-12
    ports:
      - "5445:5432"
    volumes:
      - pg_0_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=${COMMON_POSTGRESQL_POSTGRES_PASSWORD}
      - POSTGRESQL_USERNAME=${COMMON_POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${COMMON_POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${COMMON_POSTGRESQL_DATABASE}
      - REPMGR_PASSWORD=${COMMON_REPMGR_PASSWORD}
      - REPMGR_PRIMARY_HOST=${COMMON_REPMGR_PRIMARY_HOST}
      - REPMGR_PARTNER_NODES=${COMMON_REPMGR_PARTNER_NODES}
      - REPMGR_NODE_NAME=${MASTER_REPMGR_NODE_NAME}
      - REPMGR_NODE_NETWORK_NAME=${MASTER_REPMGR_NODE_NETWORK_NAME}
    networks:
      url-service-network:
        ipv4_address: 172.18.0.2

  slave-pg-1:
    image: bitnami/postgresql-repmgr:14-debian-12
    ports:
      - "5446:5432"
    volumes:
      - pg_1_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=${COMMON_POSTGRESQL_POSTGRES_PASSWORD}
      - POSTGRESQL_USERNAME=${COMMON_POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${COMMON_POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${COMMON_POSTGRESQL_DATABASE}
      - REPMGR_PASSWORD=${COMMON_REPMGR_PASSWORD}
      - REPMGR_PRIMARY_HOST=${COMMON_REPMGR_PRIMARY_HOST}
      - REPMGR_PARTNER_NODES=${COMMON_REPMGR_PARTNER_NODES}
      - REPMGR_NODE_NAME=${SLAVE_REPMGR_NODE_NAME}
      - REPMGR_NODE_NETWORK_NAME=${SLAVE_REPMGR_NODE_NETWORK_NAME}
    networks:
      url-service-network:
        ipv4_address: 172.18.0.3

  pgpool:
    image: bitnami/pgpool:4-debian-12
    ports:
      - "5437:5432"
    environment:
      - PGPOOL_BACKEND_NODES=${PGPOOL_BACKEND_NODES}
      - PGPOOL_SR_CHECK_USER=${PGPOOL_SR_CHECK_USER}
      - PGPOOL_SR_CHECK_PASSWORD=${PGPOOL_SR_CHECK_PASSWORD}
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=${PGPOOL_POSTGRES_USERNAME}
      - PGPOOL_POSTGRES_PASSWORD=${PGPOOL_POSTGRES_PASSWORD}
      - PGPOOL_ADMIN_USERNAME=${PGPOOL_ADMIN_USERNAME}
      - PGPOOL_ADMIN_PASSWORD=${PGPOOL_ADMIN_PASSWORD}
    networks:
      url-service-network:
        ipv4_address: 172.18.0.4
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4.1
    command: redis-server --requirepass redis!123
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data
    ports:
      - "6377:6379"
    networks:
      url-service-network:
        ipv4_address: 172.18.0.5
    restart: always

volumes:
  pg_0_data:
    driver: local
  pg_1_data:
    driver: local
  redis_data:
    driver: local
