version: '3.8'

x-environment:
  &url_service-env
  - POSTGRES_SERVER=${POSTGRES_SERVER}
  - POSTGRES_PORT=${POSTGRES_PORT}
  - POSTGRES_USER=${POSTGRES_USER}
  - POSTGRES_DB=${POSTGRES_DB}
  - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  - REDIS_PORT=${REDIS_PORT}
  - REDIS_SERVER=${REDIS_SERVER}
  - REDIS_PASSWORD=${REDIS_PASSWORD}
  - REDIS_EXPIRE_TIME=${REDIS_EXPIRE_TIME}

services:
  load_balancer:
    image: nginx:1.27.2-bookworm
    ports:
      - "8080:8080"
    volumes:
      - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - url_service1
      - url_service2
    networks:
      - my_network

  url_service1:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./src/.env
    environment: *url_service-env
    depends_on:
      - postgres
      - redis
    restart: always
    ports:
      - "5051:5959"
    networks:
      - my_network

  url_service2:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./src/.env
    environment: *url_service-env
    depends_on:
      - postgres
      - redis
    restart: always
    ports:
      - "5052:5959"
    networks:
      - my_network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    networks:
      - my_network
    restart: always

  redis:
    image: redis:7.4.1
    command: redis-server --requirepass redis!123
    volumes:
      - redis_data:/data
    ports:
      - "6377:6379"
    networks:
      - my_network
    restart: always

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
networks:
  my_network: