version: "3.8"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    build:
      context: .
      dockerfile: dockerfile
    networks:
      - nginx_bridge
    restart: always

networks:
  nginx_bridge:
    external: true